<a href="https://colab.research.google.com/github/MFahim-Data/Full-Stack-Data-Analytics/blob/main/PANDAS_Pivot_Table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

from google.colab import files
upload = files.upload()

Saving student.csv to student.csv

In [3]:
import pandas as pd
import numpy as np
# set the dataframe
df = pd.read_csv("student.csv")

In [8]:
# explore data
df.head()

   id        name  class  score  gender grade
0   1    John Deo   Four     75  female     B
1   2    Max Ruin  Three     85    male     A
2   3      Arnold  Three     55    male     D
3   4  Krish Star   Four     60  female     C
4   5   John Mike   Four     60  female     C

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    34 non-null     object
 2   class   34 non-null     object
 3   score   35 non-null     int64
 4   gender  33 non-null     object
 5   grade   35 non-null     object
dtypes: int64(2), object(4)
memory usage: 1.8+ KB

In [10]:
df.describe()

              id      score
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

In [11]:
# indexing & slicing
df["name"]
df[["name", "score"]]
df.iloc[:3]
df.loc[df["class"] == "Four"]

    id         name class  score  gender grade
0    1     John Deo  Four     75  female     B
3    4   Krish Star  Four     60  female     C
4    5    John Mike  Four     60  female     C
5    6    Alex John  Four     55    male     D
9   10     Big John  Four     55  female     D
15  16        Gimmy  Four     88    male     A
20  21   Babby John  Four     69  female     C
30  31  Marry Toeey  Four     88    male     A

In [13]:

# aggregation & grouping
df.groupby("class")["score"].mean()
df["class"].value_counts()
df.groupby("gender")["score"].mean()

gender
female    77.312500
male      71.588235
Name: score, dtype: float64

In [14]:
# pivot table
df.pivot_table(index="class", columns="gender", values="score")

# grade column
df["grade"] = df["score"].apply(
    lambda x: "A" if x >= 85 else
              "B" if x >= 70 else
              "C" if x >= 60 else
              "D"
)

# sorting
df.sort_values(by="score", ascending=False)

    id         name  class  score  gender grade
32  33    Kenn Rein    Six     96  female     A
11  12        Recky    Six     94  female     A
31  32    Binn Rott  Seven     90  female     A
10  11       Ronald    Six     89  female     A
30  31  Marry Toeey   Four     88    male     A
34  35   Rows Noump    Six     88  female     A
24  25     Giff Tow  Seven     88    male     A
14  15     Tade Row    NaN     88    male     A
15  16        Gimmy   Four     88    male     A
12  13          Kty  Seven     88  female     A
13  14         Bigy  Seven     88  female     A
27  28    Rojj Base  Seven     86  female     A
7    8       Asruid   Five     85    male     A
1    2     Max Ruin  Three     85    male     A
26  27          NaN  Three     81     NaN     B
29  30    Reppy Red    Six     79  female     B
25  26       Crelea  Seven     79    male     B
22  23        Herod  Eight     79    male     B
6    7  My John Rob  Fifth     78    male     B
23  24    Tiddy Now  Seven     78    male     B
8    9      Tes Qry    Six     78     NaN     B
17  18        Honny   Five     75    male     B
0    1     John Deo   Four     75  female     B
33  34     Gain Toe  Seven     69    male     C
20  21   Babby John   Four     69  female     C
19  20       Jackly   Nine     65  female     C
3    4   Krish Star   Four     60  female     C
4    5    John Mike   Four     60  female     C
2    3       Arnold  Three     55    male     D
5    6    Alex John   Four     55    male     D
9   10     Big John   Four     55  female     D
21  22       Reggid  Seven     55  female     D
28  29  Tess Played  Seven     55    male     D
16  17        Tumyu    Six     54    male     D
18  19        Tinny   Nine     18    male     D

In [ ]:
# export
df.to_csv("student_with_grades.csv", index=False)